### ISSUE TITLE
你好，我不想要数据转换功能，数据我想自己处理，应该改哪里呢？

### ISSUE THREAD

**Issue by 542604974** [pujiaxin33/JXMovableCellTableView#10]
你好，我不想要数据转换功能，数据我想自己处理，应该改哪里呢？

**Comment by 542604974** [comment]
就是那个cell会上下更换位置

**Comment by pujiaxin33** [comment]
这个数据交换也只能依照cell的交换，交换数据顺序，还能怎么处理呢？

**Comment by 542604974** [comment]
就像tableView原来的那样，变动位置，最后自己处理数据，而不是在拖动过程中交换数据

**Comment by pujiaxin33** [comment]
我为了集成简单，直接把数据源交换也内部处理了。没有把cell视图移动与数据源交换分割开。
所以你的要求，目前只有你自己修改源码实现呢。

**Comment by 542604974** [comment]
好的
