### ISSUE TITLE
特定操作下tableViewl会抖动

### ISSUE THREAD

**Issue by 1071273821** [pujiaxin33/JXMovableCellTableView#11]
当 tableView.rowHeight = UITableViewAutomaticDimension 时，cell从最下往上移动并移动到顶端，tableview会上下抖动，这个可以解决吗

**Comment by pujiaxin33** [comment]
貌似不行，最好不要用UITableViewAutomaticDimension。因为系统有时候会抽风，明明算出来是100，当有时候会先返回44，再变成100。

**Comment by 1071273821** [comment]
不用UITableViewAutomaticDimension的话，5s机型上也是会有同样的问题

**Comment by pujiaxin33** [comment]
已经修复了，重新clone仓库测试一下呢，pods晚点更新

**Comment by CoderLineChan** [comment]
你好！rowHeight 设置70以上的时候 会抖动，
