### ISSUE TITLE
tableView.rowHeight 设置高一点就会抖动。

### ISSUE THREAD

**Issue by CoderLineChan** [pujiaxin33/JXMovableCellTableView#12]
你好！直接下载你的demo， 添加heightForRowAtIndexPath方法 返回70 以上， cell 拖到两端就会抖动！！可以解决么？

**Comment by pujiaxin33** [comment]
谢谢反馈！确实有问题，目前正在分析原因。

**Comment by jianniou** [comment]
这个bug ，iOS 11后系统默认开启Self-Sizing ，把下面设置了应该就没有抖动  
self.tableView.rowHeight = 0;
self.tableView.estimatedRowHeight = 0;
self.tableView.estimatedSectionHeaderHeight = 0;
self.tableView.estimatedSectionFooterHeight = 0;

**Comment by pujiaxin33** [comment]
@jianniou 非常感谢，已经修复
