### ISSUE TITLE
关于内部移动数据源问题

### ISSUE THREAD

**Issue by CoderLineChan** [pujiaxin33/JXMovableCellTableView#13]
/只有一组
[_tempDataSource exchangeObjectAtIndex:fromIndexPath.row withObjectAtIndex:toIndexPath.row];
是否应该修改成：
//只有一组
[_tempDataSource[fromIndexPath.section] exchangeObjectAtIndex:fromIndexPath.row withObjectAtIndex:toIndexPath.row];
----------------------------------------------------------------------
这里还会有个问题：
如果外面的数据源只有一层数组， 则只能使用_tempDataSource，
如果外面的数据源是两层数组，则需要使用_tempDataSource[fromIndexPath.section]。
所以这里还需要做好多层数据源的判断。

**Comment by pujiaxin33** [comment]
请先阅读下面的api说明:
```Objective-C
/**
 *  Get the data source array of the tableView, each time you start the call to get the latest data source.
 *  The array in the data source must be a mutable array, otherwise it cannot be exchanged
 *  The format of the data source:@[@[sectionOneArray].mutableCopy, @[sectionTwoArray].mutableCopy, ....].mutableCopy
 *  Even if there is only one section, the outermost layer needs to be wrapped in an array, such as:@[@[sectionOneArray].mutableCopy].mutableCopy
 */
- (NSMutableArray *)dataSourceArrayInTableView:(JXMovableCellTableView *)tableView;
```
当年写的不太严谨，就通过注释进行了约束。

**Comment by pujiaxin33** [comment]
通过注释约束太不人性化了，后续会通过内部判断修复。

**Comment by pujiaxin33** [comment]
已经通过泛型优化了：
```Objective-C
- (NSMutableArray <NSMutableArray *> *)dataSourceArrayInTableView:(JXMovableCellTableView *)tableView;
```
