### ISSUE TITLE
jx_updateDataSourceAndCellFromIndexPath:toIndexPath:数据交换问题

### ISSUE THREAD

**Issue by haltNoShut** [pujiaxin33/JXMovableCellTableView#14]
原始数据为012345,移动5到第一个位置后数据源应为501234,但你使用[_tempDataSource[fromIndexPath.section] exchangeObjectAtIndex:fromIndexPath.row withObjectAtIndex:toIndexPath.row]所以实际变成了512340

**Comment by pujiaxin33** [comment]
当5移动到0的时候，5会依次和4、3、2、1进行交换，所以，最后是501234
