### ISSUE TITLE
不同高度cell,向上拖动问题

### ISSUE THREAD

**Issue by chenjie112** [pujiaxin33/JXMovableCellTableView#17]
不同高度的cell（cell 高度超差超过100），超过一屏幕，向上拖动较低高度的cell，在tableview滚动的时候出现，滚动到高度较高cell的地方，出现不在自动滚动。一直卡在两个cell 交换的地方。

**Comment by pujiaxin33** [comment]
能提供复现问题的代码配置吗？
或者提供一个可以复现问题的demo。

**Comment by chenjie112** [comment]
我使用的问题，今天调试了没有问题了。没有这个bug 谢谢作者了。已经star
