### ISSUE TITLE
当一组移动完后 将不能再把数据移入

### ISSUE THREAD

**Issue by Pigdada** [pujiaxin33/JXMovableCellTableView#3]
indexPathForRowAtPoint 此方法无法判断移入空行

**Comment by pujiaxin33** [comment]
你好，能否再详细一点描述问题呢？

**Comment by Pigdada** [comment]
我这里遇到一个情况  就是当第一组数据全部移动到第二组后 就无法再把任何数据移回第一组了

由于我这里只有两组cell相互移动的情况  我就重写了以下方法
-(NSIndexPath *)indexPathForRowAtPoint:(CGPoint)point;

由point点的y值来判断是第一组还是第二组
不过如果出现三组以上就不知道解决方案了

**Comment by pujiaxin33** [comment]
“我这里遇到一个情况 就是当第一组数据全部移动到第二组后 ”
该情况应该是，第一组和第二组的数据源已经全部互相交换。现在第一组的数据，就是移动前的第二组数据。
应该不会存在“就无法再把任何数据移回第一组了”情况
