### ISSUE TITLE
快速拖动cell，在高度很高的情况下，要拖动的tableViewCell跟tmpView同时存在

### ISSUE THREAD

**Issue by Rob-wang** [pujiaxin33/JXMovableCellTableView#6]
![simulator screen shot - iphone 6s - 2018-07-05 at 11 03 45](https://user-images.githubusercontent.com/6449073/42300679-3ba579ec-8044-11e8-8a60-765f178a2524.png)

-0是是唯一的，可以看到上面的0。TmpView重影了。

复现可以创建大量单组数据，然后拖动一个，快速移动下面，又快速移动上去。一直多快速移动，就能复现。在实际开发中，这个现象更容易被复现出来

**Comment by pujiaxin33** [comment]
感谢你的反馈，已经修复该bug。
