### ISSUE TITLE
请问可以只拖动cell里面的一个view，来实现数据交换吗

### ISSUE THREAD

**Issue by 542604974** [pujiaxin33/JXMovableCellTableView#9]
请问可以只拖动cell里面的一个view，来实现数据交换吗

**Comment by pujiaxin33** [comment]
那cell本身怎么处理呢？

**Comment by 542604974** [comment]
只隐藏我拖动的view

**Comment by 542604974** [comment]
因为组里面第一行cell左边有个标题

**Comment by pujiaxin33** [comment]
只拖动cell中的某个view，这个需求逻辑有点怪怪的，因为这设计到cell排序，必然是拖动cell才行。
还有就是“因为组里面第一行cell左边有个标题”，这个标题对cell排序有什么影响吗？

**Comment by 542604974** [comment]
因为组可能有多个cell,这个标题我会放在第一个cell上面

**Comment by pujiaxin33** [comment]
你可以把标题独立于cell，用header或者另一个cell实现

**Comment by 542604974** [comment]
请问怎么独立呢，而且cell直接有间距的应该怎么消除

**Comment by pujiaxin33** [comment]
cell之间没有间距，间距都是你自己的内容。你贴一张图截图看看。

**Comment by 542604974** [comment]
<img width="697" alt="2018-10-08 10 40 04" src="https://user-images.githubusercontent.com/15099430/46600579-23358400-cb1d-11e8-96ec-bc22feb96253.png">

**Comment by 542604974** [comment]
就左边那个图片，按住右边的+号移动

**Comment by 542604974** [comment]
你好，我已经解决这个问题了，感谢
